### ISSUE TITLE
"All" view is blank, also new bookmarks aren't pre-filling or showing as already saved

### ISSUE THREAD

**Issue by robhawkes** [pawelgrzybek/PinBuddy#19]
I've just installed the extension and set up my API key but I'm unable to see my existing bookmarks, nor have new bookmarks pre-filled using the browser window title, etc.

Any ideas?

![image](https://user-images.githubusercontent.com/22612/47077787-a29c1500-d1f9-11e8-9ea9-9edde0ce721d.png)
![image](https://user-images.githubusercontent.com/22612/47077810-ad56aa00-d1f9-11e8-9075-2c4d481aef3c.png)

**Comment by pawelgrzybek** [comment]
Can you right click -> inspect and send me the output of console please?

**Comment by robhawkes** [comment]
Aha! Yeah I see loads of the same error:

```
Error in response to storage.get: Error: Given action "POSTS_GET", reducer "posts" returned undefined. To ignore an action, you must explicitly return the previous state. If you want this reducer to hold no value, you can return null instead of undefined.
    at chrome-extension://ppokjacfheflhaojmndcblibahmopkfl/popup/popup.js:1:26554
    at v (chrome-extension://ppokjacfheflhaojmndcblibahmopkfl/popup/popup.js:1:24398)
    at chrome-extension://ppokjacfheflhaojmndcblibahmopkfl/popup/popup.js:6:2477
    at dispatch (chrome-extension://ppokjacfheflhaojmndcblibahmopkfl/popup/popup.js:1:27532)
    at Object.callback (chrome-extension://ppokjacfheflhaojmndcblibahmopkfl/popup/popup.js:30:37506)
    at chrome-extension://ppokjacfheflhaojmndcblibahmopkfl/popup/popup.js:30:37030
    at chrome-extension://ppokjacfheflhaojmndcblibahmopkfl/popup/popup.js:6:2468
    at Object.postsGet (chrome-extension://ppokjacfheflhaojmndcblibahmopkfl/popup/popup.js:30:36930)
    at t.value (chrome-extension://ppokjacfheflhaojmndcblibahmopkfl/popup/popup.js:30:36241)
    at fa (chrome-extension://ppokjacfheflhaojmndcblibahmopkfl/popup/popup.js:22:83784)
    at sa (chrome-extension://ppokjacfheflhaojmndcblibahmopkfl/popup/popup.js:22:79399)
    at ca (chrome-extension://ppokjacfheflhaojmndcblibahmopkfl/popup/popup.js:22:79015)
```

**Comment by pawelgrzybek** [comment]
Yes! I came across this issue before. Unfortunately this is related with `chrome.storage.local` witch is capable to store only 5mb of data. You probably have thousands of resources in your Pinboard account that all together gives a JSON data larger than 5mb.

There is nothing that I can do with it I am afraid. It is not something that plugin is not able to hande, it is a google chrome storage restriction :(
